# Generated by Django 5.2.5 on 2025-08-16 15:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employe', '0005_alter_employe_numero_telephone_alter_employe_sexe'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='entreprises',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_entreprise', models.CharField(max_length=100)),
                ('adresse_siege', models.CharField(max_length=255)),
                ('code_postal', models.CharField(max_length=20, unique=True)),
                ('ville', models.CharField(max_length=100)),
                ('pays', models.CharField(max_length=100)),
                ('telephone_entreprise', models.CharField(max_length=15, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('numero_siret', models.CharField(max_length=14, unique=True)),
                ('code_naf', models.CharField(max_length=5, unique=True)),
                ('forme_juridique', models.CharField(choices=[('SARL', 'Société à Responsabilité Limitée'), ('SA', 'Société Anonyme'), ('SAS', 'Société par Actions Simplifiée'), ('EI', 'Entreprise Individuelle'), ('EURL', 'Entreprise Unipersonnelle à Responsabilité Limitée')], default='SARL', max_length=100)),
                ('secteur_activite', models.CharField(choices=[('Industrie', 'Industrie'), ('Services', 'Services'), ('Commerce', 'Commerce'), ('Agriculture', 'Agriculture'), ('BTP', 'Bâtiment et Travaux Publics')], default='Services', max_length=100)),
                ('nombre_employes', models.PositiveIntegerField()),
                ('date_creation', models.DateField(auto_now_add=True)),
                ('date_derniere_modification', models.DateField(auto_now=True)),
                ('id_drh', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entreprise_drh', to='employe.employe')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_service', models.CharField(max_length=100)),
                ('numero_service', models.CharField(max_length=15, unique=True)),
                ('email_service', models.EmailField(max_length=254, unique=True)),
                ('budget_annuel', models.DecimalField(decimal_places=2, max_digits=15)),
                ('objecitifs_service', models.TextField()),
                ('date_creation', models.DateField(auto_now_add=True)),
                ('date_derniere_modification', models.DateField(auto_now=True)),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='entreprise.entreprises')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
