# Generated by Django 5.2.5 on 2025-08-16 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entreprise', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='services',
            old_name='objecitifs_service',
            new_name='objectifs_service',
        ),
    ]
