# Generated by Django 5.2.5 on 2025-08-15 10:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employe', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employe',
            name='age',
            field=models.PositiveIntegerField(default=25),
        ),
        migrations.AddField(
            model_name='employe',
            name='date_embauche',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employe',
            name='drh',
            field=models.CharField(default=False, max_length=50),
        ),
        migrations.AddField(
            model_name='employe',
            name='numero_telephone',
            field=models.CharField(default='0777777777', max_length=15),
        ),
        migrations.AddField(
            model_name='employe',
            name='sexe',
            field=models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin')], default='F', max_length=10),
        ),
        migrations.AlterField(
            model_name='employe',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
