# Generated by Django 5.2.5 on 2025-08-16 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employe', '0004_alter_employe_utilisateur'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employe',
            name='numero_telephone',
            field=models.CharField(max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='employe',
            name='sexe',
            field=models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=10),
        ),
    ]
