# Generated by Django 5.2.5 on 2025-08-16 15:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employe', '0005_alter_employe_numero_telephone_alter_employe_sexe'),
        ('entreprise', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employe',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employes', to='entreprise.services'),
        ),
        migrations.AlterField(
            model_name='employe',
            name='sexe',
            field=models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin')], default='Masculin', max_length=10),
        ),
    ]
